import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="grid justify-items-center">
          <Link href="/soundcloud">Soundcloud</Link>
          <Link href="/walmart">Walmart</Link>
        </div>
      </main>
    </div>
  )
}
