import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import soundCloud from '../asset/images/sound-cloud.png'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className="grid justify-items-center">
        <div>
          <Image
            src={soundCloud}
            width={500}
            height={500}
          />  
        </div>
        <div className='bg-orange-500'>
          <Link href='/checkout-details' className='text-gray-100 text-2xl p-2 w-full' >
            continue with card payment
          </Link>
        </div>
      </div>
      </main>
    </div>
  )
}
